### PR TITLE
fix: removes code of conduct

### PR DESCRIPTION
**Pull request by jpvajda**
This PR removes the code of conduct to resolve the repo-linter error.

### CODE REVIEW

**Comment by jpvajda** [comment]
@zstix do you mind given your 👍 on this?

**Comment by jpvajda** [comment]
even though it's failing Pull Request / validate nerdpack (pull_request) Failing after 5s — validate nerdpack , it should be fine as that's an old check to look for the file i removed per @jbeveland27

**Comment by jbeveland27** [comment]
@jpvajda this repo actually doesn't have the updated version of the action: https://github.com/newrelic/nr1-nimbus/blob/main/.github/workflows/pr.yml#L130

This needs to reference `newrelic/validate-nerdpack-action@v1` (and yes `v1` is correct - actions refs are a little odd like that but it allows the author to update "non breaking changes" and push a new v1 tag without making users update to a new version every time a patch fix happens).

**Comment by jpvajda** [comment]
@jbeveland27 thanks! what's the process to update a repo's version of an action?

**Comment by jbeveland27** [comment]
@jpvajda Here you go: https://github.com/newrelic/nr1-nimbus/pull/42

**Review by LizBaker — APPROVED** [review]

**Pull request merged**
